### PR TITLE
making the app more windows friendly, extra settings can be configured

### PR DESCRIPTION
**Pull request by afro1114**

### CODE REVIEW

**Comment by bcalik** [comment]
Wow a huge commit, thanks! There are some issues, I will also check.
- Settings window does not work for me, it is just white screen.
- Indentations are broken, could you please use white space instead of tabs?

**Comment by afro1114** [comment]
There is the indentation with spaces that you requested.
The settings page is working ok for me, could be os related? i'm using win 10

**Comment by afro1114** [comment]
ok, now the settings view is working in osx, it was a small fix :)

**Comment by bcalik** [comment]
Sorry I could not check it since, I am busy with work nowadays day and night.

I am merging this without checking, because I'm still busy and won't be free for a few weeks.

Anyone please check for issues and contribute.
@mathsalmi maybe you can.

**Pull request merged**
